MVCstore/Controllers/ProductsController.cs
using MVCstore.DAL;
using MVCstore.Models;
using MVCstore.ModelView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCstore.Controllers
{
    public class ProductsController : Controller
    {
        OrderDal orddal;
        ProductDal proddal;
        OrderViewModel ovm;
        int custID;
        

        // GET: Products
        public ActionResult Index()
        {
            int userID;
            if (Session != null || Session["type"] == null || !((string)Session["type"]).Equals("Customer")   )
            {
                if (Session["userID"] != null)
                    userID = (int)Session["userID"];
            }
            else
            {
                return RedirectToAction("my404", "Home");
            }
            
            return View();
        }

        // Products View
        public ActionResult getPCbyJSON()
        {
            
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            PCDal pcdal = new PCDal();
            List<PC> pcList = pcdal.PCs.ToList();   
            return Json(pcList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getPrinterByJSON()
        {
            if (Session == null || Session["type"] == null ||  !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            PrinterDal prdal = new PrinterDal();
            List<Printer> printerList = prdal.printers.ToList();
            return Json(printerList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getLaptopByJSON()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            LaptopDal lapdal = new LaptopDal();
            List<Laptop> lapList = lapdal.laptops.ToList();
            return Json(lapList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult showProducts()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            #region wrap all products in single model view (deprecated)
            /*
            List<Product> productList = new ProductDal().products.ToList();
            List<PC> pcList = new PCDal().PCs.ToList();
            List<Printer> printerList = new PrinterDal().printers.ToList();
            List<Laptop> laptopList = new LaptopDal().laptops.ToList();
            

            ProductViewModel pvm = new ProductViewModel();

            pvm.product = new Product();
            pvm.pc = new PC();
            pvm.printer = new Printer();
            pvm.laptop = new Laptop();
            

            pvm.productList = productList;
            pvm.pcList = pcList;
            pvm.printerList = printerList;
            pvm.laptopList = laptopList;
            return View(pvm);
            */
            #endregion
            return View();
        }
        /*
        public EmptyResult addToCart(int quantity, string model, int price)
        {
            Order order = new Order();

            order.CustID = "1";
            order.Model = model;
            order.Price = price;
            order.Quantity = quantity;

            orddal.orders.Add(order);
            orddal.SaveChanges();

            return new EmptyResult();
        }
        */
        
        /// <summary>
        /// checkStock: function returns product quantity
        /// </summary>
        /// function checks if products is in stock, subtracts
        ///     needed quantity from stock and updates orders table
        /// <param name="quantityToBuy"></param>
        /// <param name="model"></param>
        /// <param name="price"></param>
        /// <returns>order object: model, price, purchased quantity</returns>
        public ActionResult checkStock(int quantityToBuy, string model, int price)
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            proddal = new ProductDal();
            orddal = new OrderDal();
            Product prod = proddal.products.First(p => p.Model.Equals (model));
            
            Order order = new Order();
            order.CustID = (int)Session["userID"];
            order.Model = model;
            order.Price = price;

            if (prod.Quantity - quantityToBuy >= 0)
            {
                prod.Quantity -= quantityToBuy;
                order.Quantity = quantityToBuy;
            }
            else
            {
                order.Quantity = prod.Quantity;
                prod.Quantity = 0;
            }

            proddal.SaveChanges();
            if (order.Quantity > 0)
            {
                orddal.orders.Add(order);
                orddal.SaveChanges();
            }
            
            return Json(order, JsonRequestBehavior.AllowGet);
        }
        
        // Cart View
        /// <summary>
        /// show cart, which is all orders that were not yet shipped - clicked "cash out"
        /// </summary>
        /// <returns> order view model, list</returns>
        public ActionResult showCart()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            orddal = new OrderDal();
            ovm = new OrderViewModel();
            custID = (int)Session["userID"];
            ovm.order = new Order(); 
            ovm.orderList = orddal.orders.Where(o=> o.CustID == custID && o.shippedDate == null).ToList<Order>();
            return View(ovm);
        }

        /// <summary>
        /// add today's date to "shipped" culumn
        /// triggered by "cash out" button
        /// </summary>
        /// <param name="custID"> customer the order belongs to</param>
        public ActionResult updateShipment(int custID)
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            orddal = new OrderDal();
            List<Order> olist = orddal.orders.Where(o => o.CustID == (custID)).ToList();
            olist.ForEach(o => o.shippedDate = DateTime.Now);
            orddal.SaveChanges();
            return new EmptyResult();
        }

        // Order History View
        /// <summary>
        /// Show All Orders User has made
        /// </summary>
        /// <returns></returns>
        public ActionResult viewHistory()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            ovm = new OrderViewModel();
            orddal = new OrderDal();
            custID = (int)Session["userID"];
            ovm.order = new Order();
            ovm.orderList = orddal.orders.Where(o => o.CustID== custID).ToList<Order>();
            return View(ovm);
        }

        /// <summary>
        /// search orders by model
        /// </summary>
        /// <returns></returns>
        public ActionResult searchOrder()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Customer"))
            {
                return RedirectToAction("my404", "Home");
            }

            ovm = new OrderViewModel();
            orddal = new OrderDal();
            string searchValue = Request.Form["search_txt"].ToString();
            List<Order> olist = orddal.orders.Where(o => o.Model.Equals(searchValue)).ToList();
            ovm.orderList = olist;

            return View(ovm);
        }

        /// <summary>
        /// Delete all Session Key-Value items, and return to main menu
        /// </summary>
        /// <returns></returns>
        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Enter", "Home");
        }
    }
}

MVCstore/Controllers/StockController.cs
using MVCstore.DAL;
using MVCstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCstore.ModelView;

namespace MVCstore.Controllers
{
    public class StockController : Controller
    {
        ProductDal proddal;
        stockRequestDal stockDal;
        RestockViewModel rvm;
        int userID;


        // GET: Stock
        public ActionResult Index()
        {
            if (Session == null)
            {
                RedirectToAction("my404", "Home");
            }
            return View();
        }

        //showStock view

        /// <summary>
        /// show stock view, shows available products and link to request confirmation
        /// </summary>
        /// <returns></returns>
        public ActionResult showStock()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }
            else
            {
                userID = (int)Session["userID"];
            }
            return View();
        }
        
        /// <summary>
        /// function uses products DAL to get all products from server
        /// async request
        /// </summary>
        /// <returns>products table in JSON format</returns>
        public ActionResult getProductsByJSON()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }
            else
            {
                userID = (int)Session["userID"];
            }
            proddal = new ProductDal();
            List<Product> prodList = proddal.products.ToList();
            return Json(prodList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// function uses products DAL to get all products that ran out from server
        /// async request
        /// </summary>
        /// <returns>products with 0 quantity table in JSON format</returns>
        public ActionResult getZeroQuantityByJSON()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }
            else
            {
                userID = (int)Session["userID"];
            }
            proddal = new ProductDal();
            List<Product> prodList = proddal.products.Where(p => p.Quantity == 0).ToList();
            return Json(prodList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// add new request to restock store products
        /// will add quantity to existing requests or add new if product not found
        /// </summary>
        /// <param name="quantityToAdd"> quantity of product to be requested</param>
        /// <param name="model"> model of product to update</param>
        /// <returns></returns>
        public ActionResult restockRequest(int quantityToAdd, string model)
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }
            else
            {
                int empID = (int)Session["userID"];
            }
            stockDal = new stockRequestDal();
            StockRequest sr = null;
            
            //add: stock requests by empID
            List<StockRequest> srlist = stockDal.stockRequests.Where(s => s.arrivedDate == null).ToList();
            sr = srlist.FirstOrDefault(s => s.Model == model);
            if (sr != null)
            {
                // request exists, update quantity
                sr.Quantity += quantityToAdd;
            }
            else
            {
                sr = new StockRequest();
                // request does not exist, update quantity
                sr.Quantity = quantityToAdd;
                sr.Model = model;
                stockDal.stockRequests.Add(sr);
            }
            
            
            stockDal.SaveChanges();
            //return JSON with updates list
            return new EmptyResult();
        }


        //showRestockRequests view

        /// <summary>
        /// show all restock requests submitted by active employee
        /// </summary>
        /// <returns></returns>
        public ActionResult showRestockRequests()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }else
            {
                int empID = (int)Session["userID"];
            }

            rvm = new RestockViewModel();
            stockDal = new stockRequestDal();
            rvm.sr = new StockRequest();
            
            //add: stock requests by empID
            rvm.stockRequestList = stockDal.stockRequests.Where(sr => sr.arrivedDate == null).ToList<StockRequest>();
            return View(rvm);
        }

        /// <summary>
        /// update products quantity with active employee's request(s)
        /// </summary>
        /// <returns></returns>
        public ActionResult restockProducts()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }
            else
            {
                int empID = (int)Session["userID"];
            }

            stockDal = new stockRequestDal();
            
            //add: stock requests by empID
            List<StockRequest> srlist = stockDal.stockRequests.Where(sr => sr.arrivedDate == null).ToList();
            
            string query = "UPDATE Products " +
                            "SET " +
                            "Products.Quantity = Products.Quantity + s.Quantity " + 
                            "FROM " +
                            "Products " +
                            "INNER JOIN " +
                            "(SELECT * FROM stockOrders WHERE arrivedDate IS NULL) s " +
                            "ON " +
                            "Products.Model = s.Model; ";
            proddal = new ProductDal();
            proddal.Database.ExecuteSqlCommand(query);

            srlist.ForEach(sr => sr.arrivedDate = DateTime.Now);
            stockDal.SaveChanges();
            return new EmptyResult();
        }

        // show Requests History view

        /// <summary>
        /// show all requests, both pending and approved
        /// </summary>
        /// <returns></returns>
        public ActionResult viewRequestsHistory()
        {
            if (Session == null || Session["type"] == null || !((string)Session["type"]).Equals("Employee"))
            {
                return RedirectToAction("my404", "Home");
            }
            else
            {
                int empID = (int)Session["userID"];
            }

            stockDal = new stockRequestDal();
            rvm = new RestockViewModel();
            rvm.sr = new StockRequest();
            
            //add: stock requests by empID
            rvm.stockRequestList = stockDal.stockRequests.ToList<StockRequest>();
            return View(rvm);
        }

        /// <summary>
        /// Delete all Session Key-Value items, and return to main menu
        /// </summary>
        /// <returns></returns>
        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Enter", "Home");
        }
    }
}

MVCstore/Views/Shared/EnterLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gingos Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Borat Express", "Enter", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "GuestAbout", "Home")</li>
                    <li>@Html.ActionLink("Contact", "GuestContact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gingos Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCstore/Views/Shared/Products_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gingos Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Borat Express", "IndexCustomers", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Shop", "showProducts", "Products")</li>
                    <li>@Html.ActionLink("See Cart", "showCart", "Products")</li>
                    <li>@Html.ActionLink("Purchase History", "viewHistory", "Products")</li>
                    <li> @Html.ActionLink("Log Out", "LogOut", "Products")</li>
                    
                </ul>
            </div> 
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gingos Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCstore/Views/Shared/Stock_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gingos Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Borat Express", "IndexEmployees", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Available Products", "showStock", "Stock")</li>
                    <li>@Html.ActionLink("Pending Restock Requests", "showRestockRequests", "Stock")</li>
                    <li>@Html.ActionLink("History", "viewRequestsHistory", "Stock")</li>
                    <li> @Html.ActionLink("Log Out", "LogOut", "Stock")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gingos Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gingos Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>    
                @Html.ActionLink("Borat Express", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })             
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@{
                            if (Session["type"].Equals("Customer"))
                            {
                                Html.ActionLink("Home", "IndexCustomer", "Home");
                            }
                            else
                            { 
                                Html.ActionLink("Home", "IndexEmployee", "Home");
                            }

                         }
                    </li>
                    <li>@{
                        if (Session["type"].Equals("Customer"))
                        {
                            Html.ActionLink("About", "IndexCustomer", "Home");
                        }
                        else
                        {
                            Html.ActionLink("About", "IndexEmployee", "Home");
                        }

                        }
                    </li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gingos Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>